//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandsClothes.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int idHistory { get; set; }
        public int idMaterial { get; set; }
        public string Action { get; set; }
        public Nullable<int> OldCount { get; set; }
        public int NewCount { get; set; }
        public System.DateTime DateUpdate { get; set; }
    }
}
